// Drift gate between the hand-written `ServerEvent` union in src/types.ts and
// the shapes the server actually puts on the wire.
//
// `fixtures/wire/server-events.json` is generated by a test in the Klank server
// repo and copied here by `scripts/sync-wire-fixtures.sh`: one fully serialized
// sample per wire event, keyed by its `type`, with every `Option` populated.
//
// The union has no runtime representation, so it is read through the TypeScript
// compiler API instead of a value.
//
// ASYMMETRY, on purpose: a field the server added and the SDK has not modelled
// is caught only while the fixture carries it. Fields the server omits during
// serialization (`skip_serializing_if`, a `None` in a real payload) are
// invisible to this gate — which is exactly why the generator populates every
// `Option` and gives `mentions` a non-empty value.

import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { describe, expect, it } from 'vitest'

const here = dirname(fileURLToPath(import.meta.url))
const typesPath = join(here, '../src/types.ts')
const fixturePath = join(here, '../fixtures/wire/server-events.json')

const REFRESH = 'refresh it with `bash scripts/sync-wire-fixtures.sh [git-ref]` from the repo root'

const fixture: Record<string, Record<string, unknown>> = JSON.parse(
  readFileSync(fixturePath, 'utf8'),
)

const program = ts.createProgram([typesPath], {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  strict: true,
  noEmit: true,
})
const checker = program.getTypeChecker()
const source = program.getSourceFile(typesPath)
if (!source) throw new Error(`the TypeScript compiler could not load ${typesPath}`)
const statements = source.statements

/** The type a top-level `type X = …` or `interface X { … }` in src/types.ts declares. */
function declaredType(name: string): ts.Type {
  for (const statement of statements) {
    if (!ts.isTypeAliasDeclaration(statement) && !ts.isInterfaceDeclaration(statement)) continue
    if (statement.name.text !== name) continue
    const symbol = checker.getSymbolAtLocation(statement.name)
    if (symbol) return checker.getDeclaredTypeOfSymbol(symbol)
  }
  throw new Error(`src/types.ts no longer declares \`${name}\`; this gate needs it`)
}

interface Variant {
  declared: Set<string>
  required: Set<string>
}

/** Wire `type` → the properties src/types.ts declares for that event. */
const variants: Map<string, Variant> = (() => {
  const union = declaredType('ServerEvent')
  if (!union.isUnion()) throw new Error('`ServerEvent` in src/types.ts is no longer a union type')
  const byWireType = new Map<string, Variant>()
  for (const member of union.types) {
    const discriminant = member.getProperty('type')
    if (!discriminant) {
      throw new Error(`\`${checker.typeToString(member)}\` in the union has no \`type\` property`)
    }
    const literal = checker.getTypeOfSymbol(discriminant)
    if (!literal.isStringLiteral()) {
      throw new Error(
        `\`${checker.typeToString(member)}\` must declare \`type\` as a string literal, got ` +
          `\`${checker.typeToString(literal)}\``,
      )
    }
    const declared = new Set<string>()
    const required = new Set<string>()
    for (const property of member.getProperties()) {
      declared.add(property.getName())
      if ((property.flags & ts.SymbolFlags.Optional) === 0) required.add(property.getName())
    }
    byWireType.set(literal.value, { declared, required })
  }
  return byWireType
})()

describe('wire fixture drift gate', () => {
  it('fixture keys are exactly the members of the `ServerEvent` union', () => {
    const missingFromFixture = [...variants.keys()].filter((wire) => !(wire in fixture)).sort()
    const missingFromUnion = Object.keys(fixture)
      .filter((wire) => !variants.has(wire))
      .sort()
    expect(
      { missingFromFixture, missingFromUnion },
      `modelled in src/types.ts but absent from the fixture: [${missingFromFixture.join(', ')}] — either the server dropped the event (delete the interface and its union member) or the fixture is stale (${REFRESH}). In the fixture but not in src/types.ts: [${missingFromUnion.join(', ')}] — the server added the event; add an interface in src/types.ts and a member to the \`ServerEvent\` union.`,
    ).toEqual({ missingFromFixture: [], missingFromUnion: [] })
  })

  it('every field the server sends is declared in src/types.ts', () => {
    const undeclared: string[] = []
    for (const [wire, event] of Object.entries(fixture)) {
      const variant = variants.get(wire)
      if (!variant) continue // already reported by the key-set assertion
      for (const field of Object.keys(event)) {
        if (!variant.declared.has(field)) undeclared.push(`${wire}.${field}`)
      }
    }
    expect(
      undeclared,
      'the server sends fields src/types.ts does not declare (a rename shows up as one entry ' +
        'here and one in the next assertion): add them to the matching interface in src/types.ts.',
    ).toEqual([])
  })

  it('every non-optional property in src/types.ts is present in the fixture', () => {
    const absent: string[] = []
    for (const [wire, variant] of variants) {
      const event = fixture[wire]
      if (!event) continue // already reported by the key-set assertion
      for (const field of variant.required) {
        if (!(field in event)) absent.push(`${wire}.${field}`)
      }
    }
    expect(
      absent,
      `src/types.ts requires fields the server no longer sends: make them optional or delete them in src/types.ts, unless the fixture is simply stale (${REFRESH}).`,
    ).toEqual([])
  })

  it('every `EventAliases` target is a member of the union', () => {
    const dangling: string[] = []
    for (const alias of declaredType('EventAliases').getProperties()) {
      const target = checker.getTypeOfSymbol(alias)
      if (!target.isStringLiteral()) {
        dangling.push(`${alias.getName()} → ${checker.typeToString(target)} (not a string literal)`)
      } else if (!variants.has(target.value)) {
        dangling.push(`${alias.getName()} → ${target.value}`)
      }
    }
    expect(
      dangling,
      'these `EventAliases` entries in src/types.ts point at wire names the `ServerEvent` union ' +
        'does not contain: repoint or remove them in src/types.ts.',
    ).toEqual([])
  })

  it('every fixture entry carries the `type` it is keyed by', () => {
    const mismatched = Object.entries(fixture)
      .filter(([wire, event]) => event.type !== wire)
      .map(([wire, event]) => `${wire} carries type ${JSON.stringify(event.type)}`)
    expect(
      mismatched,
      `the fixture is keyed by wire \`type\`; these entries disagree with themselves (${REFRESH}).`,
    ).toEqual([])
  })
})
